### ISSUE TITLE
Not possible to paste

### ISSUE THREAD

**Issue by lpvm** [Teklad/spacefm-ng#17]
Hi,
When I copy or cut a file, the paste option is always dimmed.
I can drag and drop from one pane to the other, though.

**Comment by HerborenInVlammen** [comment]
Your caps lock key is likely on.  :)

**Comment by lpvm** [comment]
No, it's not the Caps Lock key.  It was happening both from `spacefm` and `spacefm-ng`.  You can check it in https://github.com/IgnorantGuru/spacefm/issues/705
