### ISSUE TITLE
spacefm-installer not updated in 1.0.6.zip

### ISSUE THREAD

**Issue by cimarronline** [Teklad/spacefm-ng#3]
Thanks so much for picking up SpaceFM. It's a great file manager, and I'm glad it's continuing to be developed.

Your 1.0.6 version builds and runs well (Manjaro/Arch). I just noticed that the `spacefm-installer` included in https://github.com/Teklad/spacefm-ng/archive/1.0.6.zip is not your new version but IgnorantGuru's version.

Keep up the good work. I'm trying to get `spacefm-ng` into AUR. (EDIT: Looks like it's already there today https://aur.archlinux.org/packages/spacefm-ng/ Thanks!)

**Comment by Teklad** [comment]
Yea... I think that was fixed after the release..... It'll make it into the next update. :p

**Comment by cimarronline** [comment]
Great. The updated installer worked well for me. A very nice feature.
