### ISSUE TITLE
Cannot connect SpaceFM to Android phone

### ISSUE THREAD

**Issue by HerborenInVlammen** [Teklad/spacefm-ng#8]
I have tried everything I can think of over the years to get SpaceFM to mount my Android devices with zero success.

Has anyone been successful in doing this?  I could use some help here :)

**Comment by behroozramezani** [comment]
Did  you  try jmtpfs?

**Comment by HerborenInVlammen** [comment]
LOL.  I just did, and it works.  None of the others worked.  The funny
thing is that jmtpfs did not show up in Synaptic when searched for. 

As usual, cannot see the forest for the trees.  :)

Thanks

**Comment by Teklad** [comment]
Oh.  So you got it working?  Are we good to call this solved? :)

**Comment by HerborenInVlammen** [comment]
Yes...
